# Generated by Django 2.2.16 on 2023-01-19 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_auto_20230119_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow',
            name='text',
            field=models.TextField(default='', verbose_name='Текст'),
            preserve_default=False,
        ),
    ]
